const Book = require("../models/bookModel"); // Book from ATD of model

exports.allBook = async (req, res, next) => {
  res.json(await Book.allBook()); //responce into router using ATD of BOOK's allBook method in json type
};

exports.addBook = async (req, res, next) => {
  let book = new Book(
    null,
    req.body.title,
    req.body.ISBN,
    req.body.publishedDate,
    req.body.author
  );
  const result = await book.addBook(); //new book using ATD BOOK model with addBook method
  book._id = result.insertedId; //new book's _id gets mongoDB's autogenerated insertedId
  res.json(book); // responce that book in json type
};

exports.getBook = async (req, res, next) => {
  res.json(await Book.getBook(req.params.id));
};

exports.updateBook = async (req, res) => {
  console.log(req.body);
  let updateBook = new Book(
    req.params.id,
    req.body.title,
    req.body.ISBN,
    req.body.publishedDate,
    req.body.author
  );
  await updateBook.update();
  res.json(updateBook);
};

exports.deleteBook = async (req, res, next) => {
  await Book.deleteBook(req.params.id);
  res.json({ _id: req.params.id });
};
